// Generated by Dagger (https://dagger.dev).
package com.example.healthassistant.core.di;

import androidx.lifecycle.ViewModel;

import com.example.healthassistant.presentation.di.ViewModelFactory;

import java.util.Map;

import javax.inject.Provider;

import dagger.internal.Factory;

@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class ViewModelFactory_Factory implements Factory<ViewModelFactory> {
  private final Provider<Map<Class<? extends ViewModel>, Provider<ViewModel>>> creatorsProvider;

  public ViewModelFactory_Factory(
          Provider<Map<Class<? extends ViewModel>, Provider<ViewModel>>> creatorsProvider) {
    this.creatorsProvider = creatorsProvider;
  }

  public static ViewModelFactory_Factory create(
          Provider<Map<Class<? extends ViewModel>, Provider<ViewModel>>> creatorsProvider) {
    return new ViewModelFactory_Factory(creatorsProvider);
  }

  public static ViewModelFactory newInstance(
          Map<Class<? extends ViewModel>, Provider<ViewModel>> creators) {
    return new ViewModelFactory(creators);
  }

  @Override
  public ViewModelFactory get() {
    return newInstance(creatorsProvider.get());
  }
}
