object Versions {
    const val kotlinVersion = "1.4.10"
    const val navigationVersion = "2.2.2"
    const val androidPluginVersion = "4.0.1"
    const val daggerVersion = "2.27"
    const val androidxLifecycleVersion = "2.2.0"
    const val appCompatVersion = "1.1.0"
    const val constraintLayoutVersion = "2.0.0-beta4"
    const val coroutinesVersion = "1.4.0"
    const val glideVersion = "4.10.0"
    const val materialVersion = "1.1.0"
    const val recyclerViewVersion = "1.1.0"
    const val roomVersion = "2.2.5"
    const val kotlinSerialization = "1.0.1"
    const val kotlinSerializationConverter = "0.8.0"
    const val okhttpVersion = "4.9.0"
    const val retrofitVersion = "2.8.1"
    const val stethoVersion = "1.5.1"
    const val timberVersion = "4.7.1"
    const val rxVersion = "2.1.1"
    const val workManagerVersion = "2.3.4"
    const val chartVersion = "v3.1.0"
    const val jUnitVersion = "4.13"
    const val mockKVersion = "1.10.0"
    const val versionsVersion = "0.36.0"
    const val scopeMobVersion = "1.2.2"
    const val dependencyAnalysis = "0.71.0"
}
