@Suppress("SpellCheckingInspection")
object Versions {
    const val kotlin = "1.4.10"
    const val navigation = "2.2.2"
    const val androidPlugin = "4.0.1"
    const val dagger = "2.27"
    const val androidxLifecycle = "2.2.0"
    const val appCompat = "1.1.0"
    const val constraintLayout = "2.0.0-beta4"
    const val coroutines = "1.4.0"
    const val glide = "4.10.0"
    const val material = "1.1.0"
    const val recyclerView = "1.1.0"
    const val room = "2.2.5"
    const val kotlinSerialization = "1.0.1"
    const val kotlinSerializationConverter = "0.8.0"
    const val okhttp = "4.9.0"
    const val retrofit = "2.8.1"
    const val stetho = "1.5.1"
    const val timber = "4.7.1"
    const val rx = "2.1.1"
    const val workManager = "2.3.4"
    const val chart = "v3.1.0"
    const val jUnit = "4.13"
    const val mockK = "1.10.0"
    const val versionsVersion = "0.36.0"
    const val scopeMob = "1.2.2"
    const val dependencyAnalysis = "0.71.0"
}
