// Generated by Dagger (https://dagger.dev).
package com.example.healthassistant.core.utils.navigation;

import com.example.healthassistant.presentation.utils.navigation.NavigationResultViewModel;

import dagger.internal.Factory;

@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class NavigationResultViewModel_Factory implements Factory<NavigationResultViewModel> {
    public static NavigationResultViewModel_Factory create() {
        return InstanceHolder.INSTANCE;
    }

    public static NavigationResultViewModel newInstance() {
        return new NavigationResultViewModel();
    }

    @Override
    public NavigationResultViewModel get() {
        return newInstance();
    }

    private static final class InstanceHolder {
        private static final NavigationResultViewModel_Factory INSTANCE = new NavigationResultViewModel_Factory();
    }
}
